### ISSUE TITLE
Fatal Error in Advanced -> Upgrade -> App Defaults

### ISSUE THREAD

**Issue by stefanomarty** [fusionpbx/fusionpbx#1799]
I get this error when trying to launch "Advanced -> Upgrade -> App Defaults":
`Fatal error: Uncaught exception 'PDOException' with message 'There is already an active transaction' in /usr/share/fusionpbx/app/dialplan/resources/classes/dialplan.php:318 Stack trace: #0 /usr/share/fusionpbx/app/dialplan/resources/classes/dialplan.php(318): PDO->beginTransaction() #1 /usr/share/fusionpbx/app/dialplan/app_defaults.php(83): dialplan->import() #2 /usr/share/fusionpbx/resources/classes/domains.php(334): include('/usr/share/fusi...') #3 /usr/share/fusionpbx/core/upgrade/index.php(89): domains->upgrade() #4 {main} thrown in /usr/share/fusionpbx/app/dialplan/resources/classes/dialplan.php on line 318`

I traced it back to commit [6700578](https://github.com/fusionpbx/fusionpbx/commit/6700578d4061728c7c8ffbe85ae733be5dbf980f).

No error if I make a hard reset to commit [7841338](https://github.com/fusionpbx/fusionpbx/commit/784133806e80253029807acfeda7b0d689998255).

The system is configured to use SQLite.

**Comment by mafoo** [comment]
I can't see how the mentioned commit is causing the issue, it is more likely you had a transaction in progress (from the reported error message) and it was a coincidence of timing when you were changing what commit to use.
If you bring your self back up to HEAD version and see if the problem persists, if it does try checking that you have no calls in progress before performing the upgrade as that could cause a transaction lock within the database. If that persists you could try restarting the switch service before performing the upgrade to force the switch to release it's existing database locks. If it persists past that you probably want to come onto the IRC to see if we can help you directly.

**Comment by stefanomarty** [comment]
Thanks for your hints, mafoo :) 
I made the suggested checks, the problem persists, must be due to something I changed to this configuration, but this is a test system I keep running only to check the new commits and I do not remember having changed anything. I made a source uograde on August 5th and since then I cannot run App Defaults, as I get that error every time.

I tracked the error back to these files:
```
/usr/share/fusionpbx/app/dialplan/resources/switch/conf/dialplan/530_talking_clock_date_and_time.xml
/usr/share/fusionpbx/app/dialplan/resources/switch/conf/dialplan/540_talking_clock_time.xml
/usr/share/fusionpbx/app/dialplan/resources/switch/conf/dialplan/550_talking_clock_date.xml
```

If I rename or move elsewhere these three files, no error, even with the system back to HEAD version. If there's at least one of these files, I get the error. Looks like there's something wrong in my system with the dialplan, the App Defaults try to load the new dialplan voices, but it hangs somewhere. I'll try again to get some help on IRC, thanks.

BTW, I noticed that this file (in app/dialplan/resources/switch/conf/dialplan):
`-rwxr-xr-x 1 www-data www-data  257 ago 15 15:09 030_is_local.xml*`

has execute permissions, is that normal? Thanks.

**Comment by bkuhls** [comment]
Hi, I have the same problem after updating my sqlite-based fusionpbx to fusionpbx 4.2 but removing dialplan/530-550*.xml did not help. Anything else I can try to debug?

**Comment by stefanomarty** [comment]
Hi, I still do not have any clue about this problem, the only thing I know is that it reappears every time a commit adds a new .xml file in `/usr/share/fusionpbx/app/dialplan/resources/switch/conf/dialplan/`

I tried to follow the program logic, but I'm not a Php expert, the only thing I understand is that "App Defaults" tries to create new dialplan voices, taking data from .xml files in `/usr/share/fusionpbx/app/dialplan/resources/switch/conf/dialplan/`

It was ok until the commit posted above, so the old .xml files are ok, but the new ones cause the App Defaults to hang. As we are the only users reporting this, I have to assume this is related to SQLite DB.

A quick and dirty way to temporarily solve the issue is to move away these new .xml files. There's a new file to move since my message above:
`250_conf-xfer.xml`

Just move it away from `/usr/share/fusionpbx/app/dialplan/resources/switch/conf/dialplan` and App Defaults will run again. I then run `service apache2 restart` if App Defaults is hanged.

I understand this is not a solution, just a trick to let App Defaults not to hang.

This is the "git status" output on my system:
```
sysname:/usr/share/fusionpbx# git status
Sul branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    app/dialplan/resources/switch/conf/dialplan/250_conf-xfer.xml
	deleted:    app/dialplan/resources/switch/conf/dialplan/530_talking_clock_date_and_time.xml
	deleted:    app/dialplan/resources/switch/conf/dialplan/540_talking_clock_time.xml
	deleted:    app/dialplan/resources/switch/conf/dialplan/550_talking_clock_date.xml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	fusionpbx.db
	phpliteadmin.config.php
	phpliteadmin.php

no changes added to commit (use "git add" and/or "git commit -a")
```
